//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastEmployee
    {
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public string post { get; set; }
        public string address { get; set; }
        public string education { get; set; }
        public string reason { get; set; }
        public int id_past_employee { get; set; }
    }
}
